### ISSUE TITLE
Add documentation parameters

### ISSUE THREAD

**Issue by pifry** [pifry/rbc#2]
There should be possible to define documentation only parameters in protocol yaml e.g. 
``` yaml
doc:
   title: some title
   footer: footer text
   header: header text
   revision: git
```
